### ISSUE TITLE
`nil` not correctly translated to `null` for SLEEK

### ISSUE THREAD

**Issue by benedictleejh** [sl-comp/SL-COMP18#10]
Whenever the translator sees a `nil`, it should get translated to `null`, but instead, it remains as `nil` in the translated output. For example, for `qf_shid_entl/01.tst.smt2`, the translated output is (showing only the affect part):

```
pred RList<y> ==  self::RefGTyp<f0:y> & nil!=self
	or  exists xp: xp::RefGTyp<f0:y> * self::RList<xp> & nil!=xp
.
```

when it should be:

```
pred RList<y> ==  self::RefGTyp<f0:y> & null!=self
	or  exists xp: xp::RefGTyp<f0:y> * self::RList<xp> & null!=xp
.
```

**Comment by slcomp** [comment]
It was indeed an issue. Now it is fixed.

**Comment by slcomp** [comment]
Translation of 'nil' fixed.
