### ISSUE TITLE
Missing consequent in SLEEK translation

### ISSUE THREAD

**Issue by benedictleejh** [sl-comp/SL-COMP18#12]
For several files, the translated output has no consequent. For example, in `qf_shls_entl/clones-01-e01.tptp.smt2`, the output is (showing only the relevant parts):

```
checkentail nil=nil & nil!=x1
	 |- .
```

This seems to mainly affect the `clones-*` benchmarks.

**Comment by slcomp** [comment]
Issue fixed, thanks.
