### ISSUE TITLE
Possibly incorrect status of test cases dll-vc06?

### ISSUE THREAD

**Issue by ghost** [sl-comp/SL-COMP18#15]
Hi,

I notice that the status of the test case [dll-vc06.smt2](https://github.com/sl-comp/SL-COMP18/blob/master/bench/qf_shid_entl/dll-vc06.smt2) in category `qf_shid_entl` should be `sat`.

The entailment in that test case can be rewritten as follow:

`x->(w,nil) * dll(w,u,x,y) * y->(z,u) & x!=w & x!=z & y!=z  |-  dll(x,y,nil,z)`

where
- the singleton heap: `x->(next, prev)`
- the inductive predicate: `dll(front, back, prev, next)`, where in the inductive case: `front != next` and `back != prev`

Then, the LHS of that entailment would need an extra condition `w!=z & x!=y` to combine `dll(w,u,x,y) * y->(z,u)` into a predicate `dll(w,y,x,z)`. The later can combine with `x->(w,nil)` to become `dll(x,y,nil,z)`.

Here, the extra condition `w!=z` **cannot be proved** by the LHS of the original entailment.

Could you please advise if my observation is correct?
Thanks!

**Comment by slcomp** [comment]
This has been discussed in the mailing list and fixed in the benchmark.
