### ISSUE TITLE
Possible wrong status of the test case qf_shidlia_entl/dll-entl-02.smt2?

### ISSUE THREAD

**Issue by ghost** [sl-comp/SL-COMP18#25]
Hi,

I suspected the status of the test case [dll-entl-02.smt2](https://github.com/sl-comp/SL-COMP18/blob/master/bench/qf_shidlia_entl/dll-entl-02.smt2) should be `sat` (currently it is `unsat`).

I rewrite the entailment in this test case as in the format of our prover Songbird as follows:

```

data RefDll_t {
    RefDll_t next;
    RefDll_t prev;
    int data_sbd;
};

pred sdll(E,P,dt1,F,L,dt2) :=
    (emp & E=F & P=L & dt1=dt2)
    \/ (exists u,dt3. E->RefDll_t{next:u,prev:P,data_sbd:dt1} *
          sdll(u,E,dt3,F,L,dt2) & dt1>dt3+1);


checkentail
sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E4,F4,x4) * sdll(E3,F3,x3,E4,F4,x4) *
sdll(E4,F4,y4,E3,F3,y3) * sdll(E3,F3,x3,E5,F5,x5) * sdll(E5,F5,y5,E3,F3,y3) *
sdll(E4,F4,x5,E6,F6,x6) & x4=x5 & x4=y4 & x3=y3
    |- sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E6,F6,x6);
```

In the last entailment, suppose that all the predicates `sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E4,F4,x4) * sdll(E3,F3,x3,E4,F4,x4) * sdll(E4,F4,y4,E3,F3,y3) * sdll(E3,F3,x3,E5,F5,x5) * sdll(E4,F4,x5,E6,F6,x6)` in the LHS are unfolded by their base case, except `sdll(E5,F5,y5,E3,F3,y3)`, then we can obtain this entailment:

```
checkentail
sdll(E5,F5,y5,E3,F3,y3) &
E1=E3 & F1=F3 & x1=x3 &
E2=E4 & F2=F4 & x2=x4 &
E3=E4 & F3=F4 & x3=x4 &
E4=E3 & F4=F3 & y4=y3 &
E3=E5 & F3=F5 & x3=x5 &
E4=E6 & F4=F6 & x5=x6 &
x4=x5 & x4=y4 & x3=y3
    |- sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E6,F6,x6);
```

which can be simplified to:

```
sdll(E5,F5,y5,E5,F5,x1) |- sdll(E5,F5,x1,E5,F5,x1) * sdll(E5,F5,x1,E5,F5,x1)
```

Now, if I choose a value of `y5` such that `y5 != x1`, then clearly, this entailment is invalid.
Hence, the status of the original test case should be `sat`.

Please let me know your opinion about this test case?

**Comment by ghost** [comment]
FYI, looking at the test case [dll-entl-01.smt2](https://github.com/sl-comp/SL-COMP18/blob/master/bench/qf_shidlia_entl/dll-entl-01.smt2), I realized that their entailments are quite similar, except that `dll-entl-01.smt2` contains an extra condition `x5=y5` (see below). Since the status of `dll-entl-01.smt2` is `unsat` (which I think that it is correct), the status of  `dll-entl-01.smt2` cannot be `unsat` either.


- dll-entl-02.smt2
```
checkentail 
sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E4,F4,x4) * sdll(E3,F3,x3,E4,F4,x4) * 
sdll(E4,F4,y4,E3,F3,y3) * sdll(E3,F3,x3,E5,F5,x5) * sdll(E5,F5,y5,E3,F3,y3) * 
sdll(E4,F4,x5,E6,F6,x6) & x4=x5 & x4=y4 & x3=y3 & x5=y5
    |- sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E6,F6,x6);
```


- dll-entl-02.smt2
```
checkentail 
sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E4,F4,x4) * sdll(E3,F3,x3,E4,F4,x4) * 
sdll(E4,F4,y4,E3,F3,y3) * sdll(E3,F3,x3,E5,F5,x5) * sdll(E5,F5,y5,E3,F3,y3) * 
sdll(E4,F4,x5,E6,F6,x6) & x4=x5 & x4=y4 & x3=y3 |- 
   sdll(E1,F1,x1,E3,F3,x3) * sdll(E2,F2,x2,E6,F6,x6);
```

**Comment by ghost** [comment]
Fore more information, I think that the status of [dll-entl-05.smt2](https://github.com/sl-comp/SL-COMP18/blob/master/bench/qf_shidlia_entl/dll-entl-05.smt2) and [dll-entl-13.smt2](https://github.com/sl-comp/SL-COMP18/blob/master/bench/qf_shidlia_entl/dll-entl-13.smt2) need to be double-checked as well. They are currently marked as `unsat`, but I think their statuses could be `sat`.

**Comment by slcomp** [comment]
Could you please explain why in dll-entl-02.smt2, the atom sdll(E1,F1,x1,E3,F3,x3) shall be unfolded for the base case? Also,  could you please post this on the mailing list? Zhilin Wu and Chong Gao should check the results.

**Comment by ghost** [comment]
Suppose that the entailment in `dll-entl-02.smt2` is valid (smt status is unsat), then any entailments derived from unfolding its predicates in the LHS should be valid. 

But the entailment obtained by unfolding all predicates by their base case, except `sdll(E5,F5,y5,E3,F3,y3)`, is invalid. 

Therefore, the original entailment is invalid (hence its smt status should be sat)

**Comment by zhilin02** [comment]
Hi tddsg,
You are right, we checked manually and agree that the status of dll-entl-02.smt is sat.

**Comment by ghost** [comment]
Hi @zhilin02 

Thanks for your comment! I created another issue related to the status of `dll-entl-05.smt` and `dll-entl-13.smt` here: https://github.com/sl-comp/SL-COMP18/issues/27.

Please let me know your opinion about these two entailments?

**Comment by slcomp** [comment]
I've changed the status of qf_shidlia_entl/dll-entl-02.smt2

**Comment by slcomp** [comment]
Fixed on GitHub
